# Generated by Django 3.1.4 on 2021-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestiontemplate',
            name='multiple_choice11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestiontemplate',
            name='multiple_choice12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.CharField(choices=[('0', 'Happy'), ('1', 'Unhappy'), ('2', 'Sick'), ('3', 'Very Ill'), ('4', 'Feeling Down'), ('5', 'Exhausted'), ('6', 'Hopeful'), ('7', 'Lonely'), ('9', 'Stressed'), ('10', 'Relaxed'), ('11', 'Agitated'), ('12', 'Energetic'), ('13', 'Blessed'), ('14', 'Hopeless'), ('15', 'Angry'), ('16', 'Worried'), ('17', 'Other'), ('18', 'Negative'), ('19', 'Neutral'), ('20', 'Positive')], max_length=2),
        ),
        migrations.AlterField(
            model_name='freetextquestiontemplate',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestiontemplate',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='numberquestiontemplate',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
