# Generated by Django 3.1.4 on 2021-10-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211021_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetextquestiontemplate',
            name='always_available',
            field=models.BooleanField(default=False, help_text='Does a new Instance get created right after the instance is answered?'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestiontemplate',
            name='always_available',
            field=models.BooleanField(default=False, help_text='Does a new Instance get created right after the instance is answered?'),
        ),
        migrations.AddField(
            model_name='numberquestiontemplate',
            name='always_available',
            field=models.BooleanField(default=False, help_text='Does a new Instance get created right after the instance is answered?'),
        ),
    ]
