# Generated by Django 3.1.4 on 2021-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211021_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='group_name',
            field=models.CharField(default='o name', help_text='only for internal use', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsection',
            name='section_name',
            field=models.CharField(default='no noa', help_text='only for internal use', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionsection',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
