# Generated by Django 3.1.4 on 2021-10-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211021_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetextquestiontemplate',
            name='frequency_time',
            field=models.CharField(blank=True, choices=[('a', 'AM'), ('p', 'PM'), ('r', 'random')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestiontemplate',
            name='frequency_time',
            field=models.CharField(blank=True, choices=[('a', 'AM'), ('p', 'PM'), ('r', 'random')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='numberquestiontemplate',
            name='frequency_time',
            field=models.CharField(blank=True, choices=[('a', 'AM'), ('p', 'PM'), ('r', 'random')], max_length=1, null=True),
        ),
    ]
