# Generated by Django 3.1.4 on 2022-03-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211021_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidStudyID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='freetextquestiontemplate',
            old_name='is_dependent_on_questions',
            new_name='is_dependent_on_question',
        ),
        migrations.RenameField(
            model_name='multiplechoicequestiontemplate',
            old_name='is_dependent_on_questions',
            new_name='is_dependent_on_question',
        ),
        migrations.RenameField(
            model_name='numberquestiontemplate',
            old_name='is_dependent_on_questions',
            new_name='is_dependent_on_question',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='freetextquestiontemplate',
            name='frequency_days',
            field=models.IntegerField(blank=True, default=1, help_text="Days until the next time the question is asked. (leave blank if it's not a routine question).", null=True),
        ),
        migrations.AlterField(
            model_name='freetextquestiontemplate',
            name='who_receives',
            field=models.CharField(choices=[('y', 'youth'), ('b', 'both youth and caretaker'), ('c', 'caregiver ONLY')], max_length=1),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestiontemplate',
            name='frequency_days',
            field=models.IntegerField(blank=True, default=1, help_text="Days until the next time the question is asked. (leave blank if it's not a routine question).", null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestiontemplate',
            name='who_receives',
            field=models.CharField(choices=[('y', 'youth'), ('b', 'both youth and caretaker'), ('c', 'caregiver ONLY')], max_length=1),
        ),
        migrations.AlterField(
            model_name='numberquestiontemplate',
            name='frequency_days',
            field=models.IntegerField(blank=True, default=1, help_text="Days until the next time the question is asked. (leave blank if it's not a routine question).", null=True),
        ),
        migrations.AlterField(
            model_name='numberquestiontemplate',
            name='who_receives',
            field=models.CharField(choices=[('y', 'youth'), ('b', 'both youth and caretaker'), ('c', 'caregiver ONLY')], max_length=1),
        ),
        migrations.CreateModel(
            name='PassiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('type', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=40)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
    ]
