# Generated by Django 3.1.4 on 2022-03-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220307_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetextquestiontemplate',
            name='start_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multiplechoicequestiontemplate',
            name='start_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberquestiontemplate',
            name='start_days',
            field=models.IntegerField(default=0),
        ),
    ]
