# Generated by Django 3.1.4 on 2022-03-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220307_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='validstudyid',
            name='type',
            field=models.CharField(choices=[('y', 'youth'), ('c', 'caretaker')], default='y', max_length=1),
        ),
    ]
