# Generated by Django 3.1.4 on 2023-06-06 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230606_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_generated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
