# Generated by Django 3.1.4 on 2023-06-06 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_profile_last_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_am_push',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_pm_push',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
