# Generated by Django 5.1.3 on 2025-02-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_project_freetextquestiontemplate_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetextquestiontemplate',
            name='who_receives',
            field=models.CharField(choices=[('y', 'Please Ignore'), ('b', 'Please Ignore2'), ('c', 'Please Ignore3')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestiontemplate',
            name='who_receives',
            field=models.CharField(choices=[('y', 'Please Ignore'), ('b', 'Please Ignore2'), ('c', 'Please Ignore3')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='numberquestiontemplate',
            name='who_receives',
            field=models.CharField(choices=[('y', 'Please Ignore'), ('b', 'Please Ignore2'), ('c', 'Please Ignore3')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('y', 'Please Ignore'), ('c', 'Please Ignore2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='validstudyid',
            name='type',
            field=models.CharField(choices=[('y', 'Please Ignore'), ('c', 'Please Ignore2')], default='y', max_length=1),
        ),
    ]
