# Generated by Django 3.1.4 on 2021-02-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='position',
            name='latest_order_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subportfolio',
            name='blocked_cash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='order_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
