# Generated by Django 3.1.4 on 2021-02-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210206_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='agg_total',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='instrument_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='latest_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
