# Generated by Django 3.1.4 on 2021-02-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210206_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subportfolio',
            name='agg_total',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='subportfolio',
            name='strategy',
            field=models.CharField(choices=[('0', 'Sector Strategy 1')], max_length=3),
        ),
    ]
