# Generated by Django 3.1.4 on 2021-02-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210206_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subportfolio',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
