# Generated by Django 3.1.4 on 2021-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_subportfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subportfolio',
            name='strategy',
            field=models.CharField(choices=[('0', 'Sector Strategy 1'), ('1', 'Keep as Cash'), ('2', 'Put into VTI')], max_length=3),
        ),
    ]
