# Generated by Django 3.1.4 on 2021-02-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_position_amount_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subportfolio',
            name='strategy',
            field=models.CharField(choices=[('0', 'Sector Strategy 1'), ('1', 'Put into VIG'), ('2', 'Put into VTI')], max_length=3),
        ),
        migrations.CreateModel(
            name='TotalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=8, max_digits=16)),
                ('date', models.DateTimeField()),
                ('subportfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.subportfolio')),
            ],
        ),
    ]
