# Generated by Django 3.1.4 on 2021-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_position_prev_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='new_cash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='new_cash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
    ]
