# Generated by Django 3.1.4 on 2021-02-26 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20210223_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='subportfolio',
            name='agg_last_rebalance',
            field=models.DateTimeField(default=datetime.datetime(2014, 9, 12, 11, 19, 54)),
        ),
        migrations.AddField(
            model_name='subportfolio',
            name='rebalance_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subportfolio',
            name='var1',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='subportfolio',
            name='var2',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='subportfolio',
            name='strategy',
            field=models.CharField(choices=[('0', 'Sector Strategy 1'), ('1', 'Put into VIG'), ('2', 'Put into VTI'), ('3', 'Sector Strategy 2'), ('4', 'Leveraged ETF Strategy')], max_length=3),
        ),
    ]
